import argparse
import os
import shutil
import subprocess
import tempfile
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent
SKETCH_DIR = BASE_DIR.parent / "expreface_ino" / "expreface"
SAMPLE_VOICE_DIR = BASE_DIR / "sample_voice"
LEGACY_SPEAKER_REFERENCE = BASE_DIR / "voiceover.wav"
DEFAULT_SPEAKER_WAV = os.getenv("DEFAULT_SPEAKER_WAV", "VO_Escoffier.wav")
MP3_BITRATE = os.getenv("TTS_MP3_BITRATE", "48k")
MP3_SAMPLE_RATE = os.getenv("TTS_MP3_SAMPLE_RATE", "24000")
TTS_MODEL_NAME = os.getenv("TTS_MODEL_NAME", "tts_models/multilingual/multi-dataset/xtts_v2")
DEFAULT_TEXT = "Hmm?"
tts = None


def ffmpeg_exe() -> str:
    env_ffmpeg = os.getenv("FFMPEG_BIN")
    if env_ffmpeg:
        return env_ffmpeg

    path_ffmpeg = shutil.which("ffmpeg")
    if path_ffmpeg:
        return path_ffmpeg

    raise RuntimeError("ffmpeg tidak ditemukan. Pastikan ffmpeg sudah ada di PATH atau set FFMPEG_BIN.")


def resolve_speaker_wav(speaker_wav: str) -> Path:
    speaker_wav = (speaker_wav or "default").strip()
    candidates = [DEFAULT_SPEAKER_WAV] if speaker_wav.lower() == "default" else [speaker_wav]

    for name in candidates:
        safe_name = Path(name).name
        if safe_name != name and speaker_wav.lower() != "default":
            raise ValueError("speaker_wav harus nama file saja, bukan path.")

        if not Path(safe_name).suffix:
            safe_name = f"{safe_name}.wav"

        candidate_path = SAMPLE_VOICE_DIR / safe_name
        if candidate_path.exists():
            return candidate_path

    if speaker_wav.lower() == "default" and LEGACY_SPEAKER_REFERENCE.exists():
        return LEGACY_SPEAKER_REFERENCE

    available = sorted(p.name for p in SAMPLE_VOICE_DIR.glob("*.wav")) if SAMPLE_VOICE_DIR.exists() else []
    suffix = f" Pilihan tersedia: {', '.join(available)}" if available else ""
    raise FileNotFoundError(f"File speaker_wav tidak ditemukan.{suffix}")


def get_tts():
    global tts
    if tts is None:
        import torch
        from TTS.api import TTS

        original_load = torch.load

        def patched_load(*args, **kwargs):
            kwargs["weights_only"] = False
            return original_load(*args, **kwargs)

        torch.load = patched_load

        device = "cuda" if torch.cuda.is_available() else "cpu"
        engine = TTS(TTS_MODEL_NAME)
        if hasattr(engine, "to"):
            engine = engine.to(device)
        tts = engine
    return tts


def convert_wav_to_short_mp3(wav_path: Path, mp3_path: Path, bitrate: str) -> None:
    cmd = [
        ffmpeg_exe(),
        "-y",
        "-hide_banner",
        "-loglevel",
        "error",
        "-i",
        str(wav_path),
        "-af",
        "silenceremove=start_periods=1:start_duration=0.03:start_threshold=-45dB,"
        "areverse,silenceremove=start_periods=1:start_duration=0.04:start_threshold=-45dB,areverse,"
        "apad=pad_dur=0.08",
        "-ar",
        MP3_SAMPLE_RATE,
        "-ac",
        "1",
        "-b:a",
        bitrate,
        str(mp3_path),
    ]

    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or "ffmpeg failed to convert filler WAV to MP3")


def write_header(mp3_path: Path, header_path: Path) -> None:
    data = mp3_path.read_bytes()
    byte_lines = []

    for offset in range(0, len(data), 16):
        chunk = data[offset : offset + 16]
        byte_lines.append("    " + ", ".join(f"0x{byte:02X}" for byte in chunk) + ",")

    header = "\n".join(
        [
            "#pragma once",
            "",
            "#include <Arduino.h>",
            "",
            "// Auto-generated by TTS-Engine/make_filler_voice.py",
            "// Keep this short; it is embedded into ESP flash with the sketch.",
            "const uint8_t fillerVoiceMp3[] PROGMEM = {",
            *byte_lines,
            "};",
            "",
            "const uint32_t fillerVoiceMp3Len = sizeof(fillerVoiceMp3);",
            "",
        ]
    )

    header_path.write_text(header, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate one embedded MP3 filler voice for expreface.")
    parser.add_argument("--text", default=os.getenv("FILLER_TEXT", DEFAULT_TEXT))
    parser.add_argument("--speaker-wav", default=os.getenv("DEFAULT_SPEAKER_WAV", "default"))
    parser.add_argument("--bitrate", default=os.getenv("FILLER_MP3_BITRATE", "32k"))
    parser.add_argument("--from-mp3", default="", help="Use an existing MP3 and only generate filler_voice.h.")
    parser.add_argument("--mp3-out", default=str(BASE_DIR / "public" / "audio" / "filler_voice.mp3"))
    parser.add_argument("--header-out", default=str(SKETCH_DIR / "filler_voice.h"))
    args = parser.parse_args()

    mp3_path = Path(args.mp3_out).resolve()
    header_path = Path(args.header_out).resolve()
    mp3_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.parent.mkdir(parents=True, exist_ok=True)

    if args.from_mp3:
        source_mp3 = Path(args.from_mp3).resolve()
        if not source_mp3.exists():
            raise FileNotFoundError(f"MP3 tidak ditemukan: {source_mp3}")
        if source_mp3 != mp3_path:
            shutil.copyfile(source_mp3, mp3_path)
        print(f"Using existing filler MP3: {source_mp3}")
    else:
        speaker_path = resolve_speaker_wav(args.speaker_wav)

        with tempfile.TemporaryDirectory(prefix="liz-filler-") as tmp_dir:
            wav_path = Path(tmp_dir) / "filler_voice.wav"

            print(f"Generating filler voice: {args.text!r}")
            get_tts().tts_to_file(
                text=args.text,
                speaker_wav=str(speaker_path),
                language="en",
                file_path=str(wav_path),
            )

            convert_wav_to_short_mp3(wav_path, mp3_path, args.bitrate)

    write_header(mp3_path, header_path)

    print(f"MP3 written: {mp3_path} ({mp3_path.stat().st_size} bytes)")
    print(f"Header written: {header_path} ({header_path.stat().st_size} bytes)")
    print(f"Runtime TTS service default bitrate is {MP3_BITRATE}; filler bitrate is {args.bitrate}.")


if __name__ == "__main__":
    main()
